version: "1.0"
services:
  node:
    image: "node"
    working_dir: /home/node/app
    volumes:
      - /home/geek/Docker-compose/app:/home/node/app
    ports:
      - 80:80
    command: >
      sh -c "npm install express mongoose mongoose-auto-increment jsonwebtoken dotenv bcrypt &&
             node server.js"
  mongo:
    image: "mongo"
    volumes:
      - /home/geek/Docker-compose/db:/data/db
