version: "1.0"
services:
  node:
    image: "node"
    working_dir: /home/node/app
    volumes:
      - /home/admin/nodejs_daneshpark/app:/home/node/app
    ports:
      - 80:80
    command: >
      sh -c "npm install express mongoose jsonwebtoken dotenv bcrypt persian-date mongoose-plugin-autoinc &&
             node server.js"
  mongo:
    image: "mongo"
    volumes:
      - /home/admin/nodejs_daneshpark/db:/data/db
